sudo: false

language: generic

os: osx
osx_image: xcode6.4

env:
  - PYVER="3.6"
  - PYVER="3.5"
  - PYVER="2.7"

install:
  # Install Miniconda.
  - curl -L https://repo.continuum.io/miniconda/Miniconda3-4.5.4-MacOSX-x86_64.sh > miniconda.sh
  - openssl md5 miniconda.sh | grep 164ec263c4070db642ce31bb45d68813
  - bash miniconda.sh -b -p ~/miniconda
  - rm miniconda.sh

  # Activate conda.
  - source ~/miniconda/etc/profile.d/conda.sh
  - conda activate base

  # Configure conda.
  - conda config --set show_channel_urls true

  # Update conda.
  - conda update -y -n root --all
  - conda install -y -n root conda-build
  - conda clean -tipsy

  # Create the test environment.
  - conda create -y -n testenv python="${PYVER}"
  - conda env update -n testenv --file environment_ci.yml
  - source activate testenv

  # Install the package and dependencies.
  - pip install -e .

# Run tests and measure test coverage.
script:
  - coverage erase
  - coverage run --source . setup.py test
  - coverage report -m

# Report coverage.
after_success:
  - source activate root
  - conda env update -n dplenv --file environment_dpl.yml
  - source activate dplenv
  - coveralls

# Disable email notifications.
notifications:
  email: false
