version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    branches:
      ignore:
        - /.*/
    steps:
      - run:
          command: exit 0

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - /.*/
